### ISSUE TITLE
Feature Request: Additional Deposit to an open channel

### ISSUE THREAD

**Issue by nickvonh** [ConnextProject/ethcalate-bidirectional-eth#1]
Are there any plans to enable additional deposits to open channels?

**Comment by rhlsthrm** [comment]
We have plans to enable this in the future, but not with this version of the contract.

**Comment by nickvonh** [comment]
Thanks for the responses!

@rhlsthrm do you mean, an update will be made to this contract in the future? Or do you mean the functionality will be a part of a contract in another repository?

@ArjunBhuptani that sounds exciting! I'll have to research this further.
Does this mean that you will be discontinuing development/support on the original hashlock contracts?

**Comment by rhlsthrm** [comment]
> do you mean, an update will be made to this contract in the future? Or do you mean the functionality will be a part of a contract in another repository?

We will most likely leave this contract as is in its stable state. A feature such as adding deposits will change the algorithms considerably so we will probably do it in another repository.

> Does this mean that you will be discontinuing development/support on the original hashlock contracts?

We are focusing on virtual channels for the time being. They seem to cover most of the use cases of hashlocks, but there are some use cases that will still work better with hashlocks. We have talked about implementing hashlocks later on as we scale up our solution, but we don't have a timeline for that yet. Please follow our progress on our virtual channel repos under the ConnextProject organization!

**Comment by nickvonh** [comment]
@rhlsthrm excellent, thank you very much!
